FROM golang:1.23.4-bookworm

WORKDIR /app

COPY users.sh /app/users.sh
RUN chmod +x /app/users.sh

COPY . /app

RUN apt-get update && apt-get install -y netcat-openbsd
RUN apt-get install -y libgeos-dev
RUN export PKG_CONFIG_PATH=/path/to/geos/lib/pkgconfig:$PKG_CONFIG_PATH
EXPOSE 3000

ENTRYPOINT ["/app/users.sh"]
