services:
  app:
    build: ./user_managment
    ports:
      - "3000:3000"
    volumes:
      - golang_data:/app
    depends_on:
      - postgres
    networks:
      - matcha
    restart: always
    env_file:
      - .env

  chat:
    build: ./chat
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - matcha
    restart: always
    env_file:
      - .env
    volumes:
      - chat_data:/app

  postgres:
    build: ./postgres
    restart: always
    image: postgres
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - matcha
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  adminer_go:
    container_name: adminer_go
    image: adminer
    restart: always
    ports:
      - 8042:8080
    networks:
      - matcha

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: "./postgres/db"
      o: bind
  golang_data:
    driver: local
    driver_opts:
      type: none
      device: "./user_managment"
      o: bind
  chat_data:
    driver: local
    driver_opts:
      type: none
      device: "./chat"
      o: bind
networks:
  matcha:
    driver: bridge
    name: matcha
