services:
  app:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - golang_data:/app
    depends_on:
      - postgres
    networks:
      - matcha
    restart: always
    env_file:
      - .env
  postgres:
    build: ./postgres
    restart: always
    image: postgres
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - matcha
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: "./postgres/db"
      o: bind
  golang_data:
    driver: local
    driver_opts:
      type: none
      device: "./backend"
      o: bind

networks:
  matcha:
    driver: bridge
    name: matcha