FROM golang:1.23.4-bookworm

WORKDIR /app

COPY go.sh /app/go.sh
RUN chmod +x /app/go.sh

COPY . /app

RUN apt-get update && apt-get install -y netcat-openbsd

EXPOSE 3000

ENTRYPOINT ["/app/go.sh"]

